"""Cursor/scroll gain applied before native touchpad injection."""
from __future__ import annotations

from windows.settings.store import SETTINGS, clamp


class GestureScaler:
    """Scale only motion generated by the Galaxy Tab.

    One finger: multiply each position delta for cursor motion.
    Two fingers: amplify only the centroid delta (pinch distance unchanged).
    Three+ fingers: pass native deltas for Windows system gestures.
    """

    W, H = 10000.0, 6000.0

    def __init__(self):
        self.prev = {}
        self.out = {}

    def convert(self, contacts):
        current = {}
        for contact in contacts:
            try:
                key = int(contact["id"])
                if key not in current and len(current) < 5:
                    current[key] = (
                        clamp(float(contact["x"]), 0, 1) * self.W,
                        clamp(float(contact["y"]), 0, 1) * self.H,
                    )
            except (KeyError, TypeError, ValueError):
                continue

        count = len(current)
        if not count:
            self.prev.clear()
            self.out.clear()
            return []

        offset = (0.0, 0.0)
        existing = current.keys() & self.prev.keys()
        if existing:
            anchor = next(iter(existing))
            offset = (
                self.out[anchor][0] - self.prev[anchor][0],
                self.out[anchor][1] - self.prev[anchor][1],
            )

        centroid_delta = (0.0, 0.0)
        if count == 2:
            ids = list(current)
            centroid_delta = tuple(
                sum(current[k][axis] - self.prev.get(k, current[k])[axis]
                    for k in ids) / 2.0 for axis in (0, 1)
            )

        output = []
        new_virtual = {}
        for contact in contacts:
            try:
                key = int(contact["id"])
            except (KeyError, TypeError, ValueError):
                continue
            if key not in current or key in new_virtual:
                continue
            raw = current[key]
            if key in self.prev:
                dx = raw[0] - self.prev[key][0]
                dy = raw[1] - self.prev[key][1]
                if count == 1:
                    gain = SETTINGS["cursor_sensitivity"]
                    dx *= gain
                    dy *= gain
                elif count == 2:
                    extra = SETTINGS["scroll_sensitivity"] - 1.0
                    dx += centroid_delta[0] * extra
                    dy += centroid_delta[1] * extra
                old = self.out[key]
                position = (old[0] + dx, old[1] + dy)
            else:
                position = (raw[0] + offset[0], raw[1] + offset[1])
            position = (
                clamp(position[0], 0, self.W),
                clamp(position[1], 0, self.H),
            )
            new_virtual[key] = position
            output.append({
                **contact,
                "x": position[0] / self.W,
                "y": position[1] / self.H,
            })

        self.prev, self.out = current, new_virtual
        return output
