"""Cursor/scroll/pinch gain applied before native touchpad injection."""
from __future__ import annotations

from windows.settings.store import SETTINGS, clamp


class GestureScaler:
    """Scale only motion generated by the Galaxy Tab.

    One finger: multiply each position delta for cursor motion.
    Two fingers:
      - scroll_sensitivity amplifies shared centroid motion (pan/scroll)
      - pinch_sensitivity amplifies distance from centroid (zoom); 1.0 = native
    Three+ fingers: pass native deltas for Windows system gestures.
    """

    W, H = 10000.0, 6000.0

    def __init__(self):
        self.prev = {}
        self.out = {}

    def convert(self, contacts):
        current = {}
        for contact in contacts:
            try:
                key = int(contact["id"])
                if key not in current and len(current) < 5:
                    current[key] = (
                        clamp(float(contact["x"]), 0, 1) * self.W,
                        clamp(float(contact["y"]), 0, 1) * self.H,
                    )
            except (KeyError, TypeError, ValueError):
                continue

        count = len(current)
        if not count:
            self.prev.clear()
            self.out.clear()
            return []

        offset = (0.0, 0.0)
        existing = current.keys() & self.prev.keys()
        if existing:
            anchor = next(iter(existing))
            offset = (
                self.out[anchor][0] - self.prev[anchor][0],
                self.out[anchor][1] - self.prev[anchor][1],
            )

        # Two-finger path: virtual = scroll-scaled centroid + pinch-scaled radius.
        if count == 2 and len(current.keys() & self.prev.keys()) == 2:
            return self._convert_two_finger(contacts, current)

        centroid_delta = (0.0, 0.0)
        if count == 2:
            ids = list(current)
            centroid_delta = tuple(
                sum(current[k][axis] - self.prev.get(k, current[k])[axis]
                    for k in ids) / 2.0 for axis in (0, 1)
            )

        output = []
        new_virtual = {}
        for contact in contacts:
            try:
                key = int(contact["id"])
            except (KeyError, TypeError, ValueError):
                continue
            if key not in current or key in new_virtual:
                continue
            raw = current[key]
            if key in self.prev:
                dx = raw[0] - self.prev[key][0]
                dy = raw[1] - self.prev[key][1]
                if count == 1:
                    gain = float(SETTINGS.get("cursor_sensitivity", 1.0))
                    dx *= gain
                    dy *= gain
                elif count == 2:
                    # One finger just joined — keep legacy scroll boost only.
                    extra = float(SETTINGS.get("scroll_sensitivity", 1.0)) - 1.0
                    dx += centroid_delta[0] * extra
                    dy += centroid_delta[1] * extra
                old = self.out[key]
                position = (old[0] + dx, old[1] + dy)
            else:
                position = (raw[0] + offset[0], raw[1] + offset[1])
            position = (
                clamp(position[0], 0, self.W),
                clamp(position[1], 0, self.H),
            )
            new_virtual[key] = position
            output.append({
                **contact,
                "x": position[0] / self.W,
                "y": position[1] / self.H,
            })

        self.prev, self.out = current, new_virtual
        return output

    def _convert_two_finger(self, contacts, current: dict) -> list:
        ids = list(current)
        a, b = ids[0], ids[1]
        c_cur = (
            (current[a][0] + current[b][0]) / 2.0,
            (current[a][1] + current[b][1]) / 2.0,
        )
        c_prev = (
            (self.prev[a][0] + self.prev[b][0]) / 2.0,
            (self.prev[a][1] + self.prev[b][1]) / 2.0,
        )
        v_c_old = (
            (self.out[a][0] + self.out[b][0]) / 2.0,
            (self.out[a][1] + self.out[b][1]) / 2.0,
        )
        scroll = float(SETTINGS.get("scroll_sensitivity", 1.0))
        pinch = float(SETTINGS.get("pinch_sensitivity", 1.0))
        v_c = (
            v_c_old[0] + (c_cur[0] - c_prev[0]) * scroll,
            v_c_old[1] + (c_cur[1] - c_prev[1]) * scroll,
        )

        output = []
        new_virtual = {}
        for contact in contacts:
            try:
                key = int(contact["id"])
            except (KeyError, TypeError, ValueError):
                continue
            if key not in current or key in new_virtual:
                continue
            raw = current[key]
            rel = (raw[0] - c_cur[0], raw[1] - c_cur[1])
            position = (
                clamp(v_c[0] + pinch * rel[0], 0, self.W),
                clamp(v_c[1] + pinch * rel[1], 0, self.H),
            )
            new_virtual[key] = position
            output.append({
                **contact,
                "x": position[0] / self.W,
                "y": position[1] / self.H,
            })

        self.prev, self.out = current, new_virtual
        return output
