"""Galaxy Trackpad v0.8 - live, mouse-independent cursor & scroll gain.

Place alongside previously tested modules in C:\\touchpad\\test_files:
  galaxytrackpad_gui_v06.py, galaxytrackpad_gui_v07.py,
  launch_v04.py, touchpad_live_v02.py, touchpad_lab.py,
  touchpad_v04.html, galaxytrackpad_settings.json.

Run: python galaxytrackpad_v08.py
Uses --engine internally. Does not modify v0.7 or Windows global mouse settings.
"""
import asyncio
import json
import logging
import math
import socket
import sys
import threading
from functools import partial
from http.server import ThreadingHTTPServer
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SETTINGS_PATH = ROOT / "galaxytrackpad_settings.json"
DEFAULTS = {"cursor_sensitivity": 1.0, "scroll_sensitivity": 1.0,
            "pen_enabled": True}
SETTINGS = DEFAULTS.copy()


def reload_settings():
    """Live changes affect subsequent touch deltas, never Windows mouse config."""
    data = {}
    try:
        data = json.loads(SETTINGS_PATH.read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            data = {}
    except (FileNotFoundError, OSError, ValueError):
        pass
    def gain(name):
        try:
            value = float(data.get(name, 1.0))
            return clamp(value, 0.5, 2.0) if math.isfinite(value) else 1.0
        except (TypeError, ValueError):
            return 1.0

    SETTINGS.update({
        "cursor_sensitivity": gain("cursor_sensitivity"),
        "scroll_sensitivity": gain("scroll_sensitivity"),
        "pen_enabled": bool(data.get("pen_enabled", True)),
    })
    print("[SETTINGS] Cursor={:.2f}x Scroll={:.2f}x (Pen: next START)".format(
        SETTINGS["cursor_sensitivity"], SETTINGS["scroll_sensitivity"]), flush=True)


def clamp(value, low, high):
    return max(low, min(high, value))


class GestureScaler:
    """Scale only motion generated by the Galaxy Tab.

    One finger: multiply each position delta for cursor motion.
    Two fingers: multiply only the centroid delta, preserving inter-finger
    distance (so native pinch stays at its ordinary scale).
    Three+ fingers: pass native deltas for Windows system gestures.
    """
    W, H = 10000.0, 6000.0

    def __init__(self):
        self.prev = {}  # Browser pointer ID -> last raw position
        self.out = {}   # Browser pointer ID -> last forwarded position

    def convert(self, contacts):
        current = {}
        for contact in contacts:
            try:
                key = int(contact["id"])
                if key not in current and len(current) < 5:
                    current[key] = (
                        clamp(float(contact["x"]), 0, 1) * self.W,
                        clamp(float(contact["y"]), 0, 1) * self.H,
                    )
            except (KeyError, TypeError, ValueError):
                continue

        count = len(current)
        if not count:
            self.prev.clear()
            self.out.clear()
            return []

        # Preserve the existing virtual offset as new fingers join.
        offset = (0.0, 0.0)
        existing = current.keys() & self.prev.keys()
        if existing:
            anchor = next(iter(existing))
            offset = (
                self.out[anchor][0] - self.prev[anchor][0],
                self.out[anchor][1] - self.prev[anchor][1],
            )

        # On 2 fingers, amplify only the shared movement, not the distance
        # between the fingers. This avoids enlarging pinch zoom itself.
        centroid_delta = (0.0, 0.0)
        if count == 2:
            ids = list(current)
            centroid_delta = tuple(
                sum(current[k][axis] - self.prev.get(k, current[k])[axis]
                    for k in ids) / 2.0 for axis in (0, 1)
            )

        output = []
        new_virtual = {}
        for contact in contacts:
            try:
                key = int(contact["id"])
            except (KeyError, TypeError, ValueError):
                continue
            if key not in current or key in new_virtual:
                continue
            raw = current[key]
            if key in self.prev:
                dx = raw[0] - self.prev[key][0]
                dy = raw[1] - self.prev[key][1]
                if count == 1:
                    gain = SETTINGS["cursor_sensitivity"]
                    dx *= gain
                    dy *= gain
                elif count == 2:
                    extra = SETTINGS["scroll_sensitivity"] - 1.0
                    dx += centroid_delta[0] * extra
                    dy += centroid_delta[1] * extra
                old = self.out[key]
                position = (old[0] + dx, old[1] + dy)
            else:
                position = (raw[0] + offset[0], raw[1] + offset[1])
            position = (
                clamp(position[0], 0, self.W),
                clamp(position[1], 0, self.H),
            )
            new_virtual[key] = position
            output.append({**contact, "x": position[0] / self.W,
                           "y": position[1] / self.H})

        self.prev, self.out = current, new_virtual
        return output


async def engine_with_control():
    """Build on v0.2's already-tested WebSocket, touch, and S Pen engines."""
    import touchpad_live_v02 as original
    old_bridge = original.TouchpadBridge

    class ScaledTouchpad(old_bridge):
        def __init__(self):
            super().__init__()
            self.scaler = GestureScaler()

        def update(self, raw_contacts):
            return super().update(self.scaler.convert(raw_contacts))

    original.TouchpadBridge = ScaledTouchpad
    original.ENABLE_PEN = SETTINGS["pen_enabled"]  # Pen toggle on next START.

    stopped = asyncio.Event()

    async def control(reader, writer):
        try:
            cmd = (await asyncio.wait_for(reader.readline(), 3)).strip()
            if cmd == b"RELOAD":
                reload_settings()
                writer.write(b"OK\n")
            elif cmd == b"STOP":
                print("[GUI] Shutdown requested", flush=True)
                stopped.set()
                writer.write(b"OK\n")
            else:
                writer.write(b"UNKNOWN\n")
            await writer.drain()
        finally:
            writer.close()
            await writer.wait_closed()

    server = await asyncio.start_server(control, "127.0.0.1", 8767)
    print("[OK] GUI control ready: 8767", flush=True)
    engine = asyncio.create_task(original.main())
    stop_task = asyncio.create_task(stopped.wait())
    try:
        done, _ = await asyncio.wait((engine, stop_task),
                                     return_when=asyncio.FIRST_COMPLETED)
        if engine in done:
            await engine  # Surface an unexpected engine failure.
    finally:
        engine.cancel()
        stop_task.cancel()
        for task in (engine, stop_task):
            try:
                await task
            except asyncio.CancelledError:
                pass
        server.close()
        await server.wait_closed()
        print("[GUI] Control server stopped", flush=True)


def engine_main():
    import launch_v04 as old
    reload_settings()
    for port in (8765, 8766, 8767):
        old.assert_port_available(port)
    if not old.ADB.is_file():
        raise FileNotFoundError(old.ADB)
    for name in ("touchpad_lab.py", "touchpad_live_v02.py", "touchpad_v04.html"):
        if not (ROOT / name).is_file():
            raise FileNotFoundError(name)

    stop = threading.Event()
    httpd = None
    watcher = None
    ws_logger = logging.getLogger("websockets.server")
    quiet_expected = old.IgnoreExpectedUSBDisconnect()
    ws_logger.addFilter(quiet_expected)
    try:
        httpd = ThreadingHTTPServer(
            ("127.0.0.1", 8765),
            partial(old.QuietHandler, directory=str(ROOT)))
        threading.Thread(target=httpd.serve_forever, daemon=True).start()
        watcher = threading.Thread(target=old.usb_watcher, args=(stop,), daemon=True)
        watcher.start()
        print("[OK] HTTP + USB watcher started", flush=True)
        asyncio.run(engine_with_control())
    except KeyboardInterrupt:
        print("[EXIT] Keyboard interrupt", flush=True)
    finally:
        stop.set()
        if watcher:
            watcher.join(timeout=3)
        if httpd:
            httpd.shutdown()
            httpd.server_close()
        ws_logger.removeFilter(quiet_expected)
        print("[EXIT] Servers stopped", flush=True)


def gui_main():
    from PySide6.QtCore import QProcess, QTimer
    from PySide6.QtNetwork import QTcpSocket
    from PySide6.QtWidgets import QApplication, QLabel, QMessageBox, QSystemTrayIcon
    import galaxytrackpad_gui_v06 as gui6
    import galaxytrackpad_gui_v07 as gui7

    base = getattr(gui7, "GalaxyTrackpadTrayWindow", None)
    if base is None:
        base = gui7.TrackpadWindow

    class Window(base):
        def __init__(self):
            self._reload_timer = None
            self._reload_socket = None
            super().__init__()
            self.setWindowTitle("Galaxy Trackpad v0.8")
            self._reload_timer = QTimer(self)
            self._reload_timer.setSingleShot(True)
            self._reload_timer.timeout.connect(self.apply_changes)
            for label in self.findChildren(QLabel):
                label.setText(label.text()
                    .replace("TOUCHPAD  ·  SETTINGS PREVIEW", "TOUCHPAD  ·  LIVE SETTINGS")
                    .replace("S PEN  ·  SETTINGS PREVIEW", "S PEN  ·  RESTART TO APPLY")
                    .replace("Settings are saved but do not affect the engine yet",
                             "Cursor/scroll: live  ·  S Pen: next START")
                    .replace("Settings preview only",
                             "Cursor/scroll: live  ·  S Pen: next START"))

        def save_settings(self):
            super().save_settings()  # Keep the existing, tested JSON UI.
            if (self._reload_timer is not None and self.control_ready and
                    self.process.state() != QProcess.ProcessState.NotRunning):
                self._reload_timer.start(250)  # Coalesce slider movements.

        def apply_changes(self):
            if not self.control_ready or self.stop_pending:
                return
            if self._reload_socket is not None:
                self._reload_socket.abort()
                self._reload_socket.deleteLater()
            sock = QTcpSocket(self)
            self._reload_socket = sock
            sock.connected.connect(lambda: sock.write(b"RELOAD\n"))
            sock.readyRead.connect(lambda: self.reload_reply(sock))
            sock.errorOccurred.connect(lambda error: self.reload_error(sock))
            sock.connectToHost("127.0.0.1", 8767)
            QTimer.singleShot(2500, lambda: self.reload_timeout(sock))

        def reload_reply(self, sock):
            reply = bytes(sock.readAll()).strip()
            if reply != b"OK":
                self.log(f"Settings update response: {reply!r}")
            sock.disconnectFromHost()
            if sock is self._reload_socket:
                self._reload_socket = None
            sock.deleteLater()

        def reload_error(self, sock):
            if sock is self._reload_socket and self.control_ready:
                self.log("Settings could not be applied: " + sock.errorString())
                self._reload_socket = None
                sock.deleteLater()

        def reload_timeout(self, sock):
            if sock is self._reload_socket:
                sock.abort()
                self._reload_socket = None
                sock.deleteLater()
                if self.control_ready:
                    self.log("Settings update timed out; try moving the slider again")

        def start_engine(self):
            # Same tested QProcess logic as v0.6/0.7; only change is --engine.
            if self.process.state() != QProcess.ProcessState.NotRunning:
                return
            self.output_bytes.clear()
            self.control_ready = False
            self.stop_pending = False
            self.stop_acknowledged = False
            self.start_button.setEnabled(False)
            self.stop_button.setEnabled(False)
            self.set_status("●  Starting...", "Initializing", "Initializing")
            self.log("---- Starting v0.8 engine ----")
            self.process.setWorkingDirectory(str(ROOT))
            self.process.start(sys.executable, ["-u", str(Path(__file__).resolve()), "--engine"])
            QTimer.singleShot(20000, self.warn_if_not_ready)
            if hasattr(self, "refresh_tray"):
                self.refresh_tray()
            if hasattr(self, "update_tray"):
                self.update_tray()

    app = QApplication(sys.argv)
    app.setStyle("Fusion")
    if QSystemTrayIcon.isSystemTrayAvailable():
        app.setQuitOnLastWindowClosed(False)
    window = Window()
    window.show()
    sys.exit(app.exec())


if __name__ == "__main__":
    if "--engine" in sys.argv:
        engine_main()
    else:
        gui_main()
